#ifndef DEVICE_TYPE_H
#define DEVICE_TYPE_H

typedef enum
{
	MULTIMEDIA_CONTROLLER = 0,
	DOOR_LOCKER = 1,
	LIGHT_CONTROLLER = 2,
	CURTAINS_CONTROLLER = 3,
	IR_REMOTE = 4,
	MOTION_DETECTOR = 5,
	HEATER_CONTROLLER = 6

} DEVICE_TYPE_ENUM;

#endif // DEVICE_TYPE_H